import { Creators as ClinicalNotesCreators } from "./clinicalNotes";
import { Creators as DrugsCreators } from "./drugs";
import { Creators as InterventionCreators } from "./intervention";
import { Creators as MemoryCreators } from "./memory";
import { Creators as OutliersCreators } from "./outliers";
import { Creators as PatientCentralCreators } from "./patientCentral";
import { Creators as PrescriptionDrugsCreators } from "./prescriptionDrugs";
import { Creators as PrescriptionsCreators } from "./prescriptions";

import { reset as adminMemoryReset } from "features/admin/Memory/MemorySlice";
import { reset as adminInterventionReasonsReset } from "features/admin/InterventionReason/InterventionReasonSlice";
import { reset as adminDrugAttributesReset } from "features/admin/DrugAttributes/DrugAttributesSlice";
import { reset as adminIntegrationReset } from "features/admin/Integration/IntegrationSlice";
import { reset as adminSegmentReset } from "features/admin/Segment/SegmentSlice";
import { reset as adminExamReset } from "features/admin/Exam/ExamSlice";
import { reset as adminFrequencyReset } from "features/admin/Frequency/FrequencySlice";
import { reset as adminUnitConversionReset } from "features/admin/UnitConversion/UnitConversionSlice";
import { reset as adminIntegrationStatusReset } from "features/admin/IntegrationStatus/IntegrationStatusSlice";
import { reset as adminIntegrationConfigReset } from "features/admin/IntegrationConfig/IntegrationConfigSlice";
import { reset as adminIntegrationRemoteReset } from "features/admin/IntegrationRemote/IntegrationRemoteSlice";
import { reset as adminSubstanceReset } from "features/admin/Substance/SubstanceSlice";
import { reset as adminRelationReset } from "features/admin/Relation/RelationsSlice";
import { reset as adminDrugReferenceDrawerReset } from "features/admin/DrugReferenceDrawer/DrugReferenceDrawerSlice";
import { reset as adminMeasureUnitReset } from "features/admin/MeasureUnit/MeasureUnitSlice";
import { reset as adminTagReset } from "features/admin/Tag/TagSlice";
import { reset as adminProtocolReset } from "features/admin/Protocol/ProtocolSlice";
import { reset as adminReportReset } from "features/admin/Report/ReportSlice";
import { reset as adminGlobalMemoryReset } from "features/admin/GlobalMemory/GlobalMemorySlice";
import { reset as adminGlobalExamReset } from "features/admin/GlobalExam/GlobalExamSlice";

import { reset as drugFormStatusReset } from "features/drugs/DrugFormStatus/DrugFormStatusSlice";
import { reset as listsReset } from "features/lists/ListsSlice";
import { reset as memoryDraftReset } from "features/memory/MemoryDraft/MemoryDraftSlice";
import { reset as memoryFilterReset } from "features/memory/MemoryFilter/MemoryFilterSlice";
import { reset as serverActionsReset } from "features/serverActions/ServerActionsSlice";
import { reset as summaryReset } from "features/summary/SummarySlice";
import { reset as drugMeasureUnitsReset } from "features/drugs/DrugMeasureUnits/DrugMeasureUnitsSlice";
import { reset as scoreWizardReset } from "features/outliers/ScoreWizard/ScoreWizardSlice";
import { reset as prescriptionv2Reset } from "features/prescription/PrescriptionSlice";
import { reset as drugAttributesFormReset } from "features/drugs/DrugAttributesForm/DrugAttributesFormSlice";
import { reset as supportReset } from "features/support/SupportSlice";
import { reset as interventionOutcomeReset } from "features/intervention/InterventionOutcome/InterventionOutcomeSlice";
import { reset as userAdminReset } from "features/userAdmin/UserAdminSlice";
import { reset as examsModalReset } from "features/exams/ExamModal/ExamModalSlice";
import { reset as examsFormReset } from "features/exams/ExamForm/ExamFormSlice";
import { reset as switchSchemaReset } from "features/switchSchema/SwitchSchemaSlice";

import { reset as reportsReset } from "features/reports/ReportsSlice";
import { reset as patientDayReportReset } from "features/reports/PatientDayReport/PatientDayReportSlice";
import { reset as prescriptionReportReset } from "features/reports/PrescriptionReport/PrescriptionReportSlice";
import { reset as interventionReportReset } from "features/reports/InterventionReport/InterventionReportSlice";
import { reset as prescriptionAuditReportReset } from "features/reports/PrescriptionAuditReport/PrescriptionAuditReportSlice";
import { reset as economyReportReset } from "features/reports/EconomyReport/EconomyReportSlice";
import { reset as cultureReportReset } from "features/reports/CultureReport/CultureReportSlice";
import { reset as antimicrobialHistoryReportReset } from "features/reports/AntimicrobialHistoryReport/AntimicrobialHistoryReportSlice";
import { reset as prescriptionHistoryReportReset } from "features/reports/PrescriptionHistoryReport/PrescriptionHistoryReportSlice";
import { reset as alertListReportReset } from "features/reports/AlertListReport/AlertListReportSlice";
import { reset as examsRawSearchReset } from "features/reports/ExamsRawSearchReport/ExamsRawSearchReportSlice";
import { reset as patientObservationReportReset } from "features/reports/PatientObservationReport/PatientObservationReportSlice";
import { reset as integrationNifiLintReportReset } from "features/reports/IntegrationNifiLintReport/IntegrationNifiLintReportSlice";
import { reset as patientDayConsolidatedReportReset } from "features/reports/PatientDayConsolidatedReport/PatientDayConsolidatedReportSlice";

import { reset as regulationPrioritizationReset } from "features/regulation/Prioritization/PrioritizationSlice";
import { reset as regulationReset } from "features/regulation/Regulation/RegulationSlice";
import { reset as regulationFormReset } from "features/regulation/RegulationForm/RegulationFormSlice";
import { reset as regulationAttributeReset } from "features/regulation/RegulationAttribute/RegulationAttributeSlice";
import { reset as regulationIndicatorsPanelReportReset } from "features/regulation/IndicatorsPanelReport/IndicatorsPanelReportSlice";

const { clinicalNotesReset } = ClinicalNotesCreators;
const { drugsReset } = DrugsCreators;
const { interventionReset } = InterventionCreators;
const { memoryReset } = MemoryCreators;
const { outliersReset } = OutliersCreators;
const { patientCentralReset } = PatientCentralCreators;
const { prescriptionDrugsReset } = PrescriptionDrugsCreators;
const { prescriptionsReset } = PrescriptionsCreators;

export const resetReduxState = (dispatch) => {
  dispatch(adminInterventionReasonsReset());
  dispatch(adminMemoryReset());
  dispatch(adminFrequencyReset());
  dispatch(adminDrugAttributesReset());
  dispatch(adminIntegrationReset());
  dispatch(adminSegmentReset());
  dispatch(adminExamReset());
  dispatch(adminFrequencyReset());
  dispatch(adminUnitConversionReset());
  dispatch(adminIntegrationStatusReset());
  dispatch(adminIntegrationConfigReset());
  dispatch(adminIntegrationRemoteReset());
  dispatch(adminSubstanceReset());
  dispatch(adminRelationReset());
  dispatch(adminDrugReferenceDrawerReset());
  dispatch(adminMeasureUnitReset());
  dispatch(adminTagReset());
  dispatch(adminProtocolReset());
  dispatch(adminReportReset());
  dispatch(adminGlobalMemoryReset());
  dispatch(adminGlobalExamReset());

  dispatch(clinicalNotesReset());
  dispatch(drugsReset());
  dispatch(interventionReset());
  dispatch(memoryReset());
  dispatch(outliersReset());
  dispatch(patientCentralReset());
  dispatch(prescriptionDrugsReset());
  dispatch(prescriptionsReset());
  dispatch(reportsReset());
  dispatch(drugFormStatusReset());
  dispatch(listsReset());
  dispatch(memoryDraftReset());
  dispatch(memoryFilterReset());
  dispatch(serverActionsReset());
  dispatch(summaryReset());
  dispatch(drugMeasureUnitsReset());
  dispatch(scoreWizardReset());
  dispatch(prescriptionv2Reset());
  dispatch(drugAttributesFormReset());
  dispatch(supportReset());
  dispatch(interventionOutcomeReset());
  dispatch(userAdminReset());
  dispatch(examsModalReset());
  dispatch(examsFormReset());
  dispatch(switchSchemaReset());

  dispatch(reportsReset());
  dispatch(patientDayReportReset());
  dispatch(prescriptionReportReset());
  dispatch(interventionReportReset());
  dispatch(prescriptionAuditReportReset());
  dispatch(economyReportReset());
  dispatch(cultureReportReset());
  dispatch(antimicrobialHistoryReportReset());
  dispatch(prescriptionHistoryReportReset());
  dispatch(alertListReportReset());
  dispatch(examsRawSearchReset());
  dispatch(patientObservationReportReset());
  dispatch(integrationNifiLintReportReset());
  dispatch(patientDayConsolidatedReportReset());

  dispatch(regulationPrioritizationReset());
  dispatch(regulationReset());
  dispatch(regulationFormReset());
  dispatch(regulationAttributeReset());
  dispatch(regulationIndicatorsPanelReportReset());
};
