/**
 * DOM side of the help mode: turning a picked element into a selector that
 * survives builds, and finding the element a selector points at.
 *
 * Styled-components class names are hashed per build and antd renames its
 * internal classes between versions, so a selector only rests on attributes
 * written in our own code or derived from our keys:
 *
 *   data-kb="prescription.drugs"   anchor placed on purpose for the help mode
 *   data-testid, id                (ids generated by antd/React are skipped)
 *   class="gtm-..."                analytics hooks, kept stable for tracking
 *   data-node-key                  antd tab, from the tab key
 *   data-menu-id                   antd menu item, from the item key
 *   name                           form fields
 *
 * An element without any of them can still be picked exactly, through its
 * position under the closest stable ancestor, but that selector is fragile:
 * any change in the markup around it stops it from matching.
 *
 * Modals and drawers are portaled straight under <body>, in the order they
 * were first opened, so a position under <body> means nothing: a path inside
 * one starts at the modal (its data-kb, or antd's modal classes) instead.
 */

// every node the help mode renders lives under this root, so it is never
// picked, highlighted or mistaken for the page's own content
export const HELP_LAYER_ID = "nh-help-mode-layer";

export interface IPickedElement {
  selector: string;
  // the element the selector points at, which may be an ancestor of the one
  // under the cursor
  element: Element;
  fragile: boolean;
}

// ids generated at runtime by React (useId), antd and rc-components
const GENERATED_ID = /^(rc[-_]|:|«|_r_|react-|ant-)|\d{3,}/;
const MENU_ID = /^rc-menu-uuid-[^-]+-(.+)$/;
const MAX_DEPTH = 15;

// roots antd portals modals and drawers into: a structural path stops there
const PORTAL_ROOTS = ["ant-modal-root", "ant-drawer"];
// parts of a modal/drawer kept by name in a structural path, so it does not
// depend on the wrappers antd renders around them
const PORTAL_PARTS = [
  ...PORTAL_ROOTS,
  "ant-modal-wrap",
  "ant-modal",
  "ant-modal-container",
  "ant-modal-content",
  "ant-modal-header",
  "ant-modal-body",
  "ant-modal-footer",
  "ant-drawer-content-wrapper",
  "ant-drawer-header",
  "ant-drawer-body",
  "ant-drawer-footer",
];

const quote = (value: string) => `"${value.replace(/["\\]/g, "\\$&")}"`;

export const isInsideHelpLayer = (node: Node | null) =>
  !!node &&
  !!(node instanceof Element ? node : node.parentElement)?.closest(
    `#${HELP_LAYER_ID}`,
  );

/**
 * Selector of the element built from its stable attributes, or null
 */
const stableSelector = (element: Element): string | null => {
  const kb = element.getAttribute("data-kb");
  if (kb) return `[data-kb=${quote(kb)}]`;

  const testId = element.getAttribute("data-testid");
  if (testId) return `[data-testid=${quote(testId)}]`;

  const id = element.getAttribute("id");
  if (id && !GENERATED_ID.test(id)) return `[id=${quote(id)}]`;

  const gtm = Array.from(element.classList).find((name) =>
    name.startsWith("gtm-"),
  );
  if (gtm) return `.${CSS.escape(gtm)}`;

  const tabKey = element.getAttribute("data-node-key");
  if (tabKey) return `[data-node-key=${quote(tabKey)}]`;

  const menuKey = element.getAttribute("data-menu-id")?.match(MENU_ID)?.[1];
  if (menuKey) return `[data-menu-id$=${quote(`-${menuKey}`)}]`;

  const name = element.getAttribute("name");
  if (name && /^(INPUT|SELECT|TEXTAREA)$/.test(element.tagName)) {
    return `${element.tagName.toLowerCase()}[name=${quote(name)}]`;
  }

  return null;
};

const queryAll = (selector: string): Element[] => {
  try {
    return Array.from(document.querySelectorAll(selector)).filter(
      (node) => !isInsideHelpLayer(node),
    );
  } catch {
    // a selector saved by hand, or by a browser that parses it differently
    return [];
  }
};

/**
 * The element's stable selector, prefixed by the stable ancestors that narrow
 * it down (a tab key such as "1" repeats across tab sets). When it still
 * repeats, as a button on every row does, the help mode shows the first
 * visible match.
 */
const scopedSelector = (element: Element, own: string): string => {
  let selector = own;
  let count = queryAll(selector).length;
  let ancestor = element.parentElement;

  for (let depth = 0; ancestor && count > 1 && depth < MAX_DEPTH; depth += 1) {
    const ancestorSelector = stableSelector(ancestor);

    if (ancestorSelector) {
      const scoped = `${ancestorSelector} ${selector}`;
      const scopedCount = queryAll(scoped).length;

      if (scopedCount < count) {
        selector = scoped;
        count = scopedCount;
      }
    }

    ancestor = ancestor.parentElement;
  }

  return selector;
};

const portalPart = (element: Element) =>
  PORTAL_PARTS.find((name) => element.classList.contains(name));

const structuralStep = (element: Element) => {
  const tag = element.tagName.toLowerCase();
  const part = portalPart(element);

  if (part) return `${tag}.${part}`;

  // the help mode's own layer comes and goes: it must not shift positions
  const siblings = Array.from(element.parentElement?.children ?? []).filter(
    (sibling) =>
      sibling.tagName === element.tagName && sibling.id !== HELP_LAYER_ID,
  );

  return siblings.length > 1
    ? `${tag}:nth-of-type(${siblings.indexOf(element) + 1})`
    : tag;
};

/**
 * The element itself, by position under its closest stable ancestor
 */
const exactSelector = (target: Element): IPickedElement => {
  const steps: string[] = [];
  let node: Element | null = target;

  for (let depth = 0; node && depth < MAX_DEPTH; depth += 1) {
    if (node === document.body) {
      return {
        selector: ["body", ...steps].join(" > "),
        element: target,
        fragile: true,
      };
    }

    const own = stableSelector(node);
    if (own) {
      const anchor = scopedSelector(node, own);

      return {
        selector: [anchor, ...steps].join(" > "),
        element: target,
        fragile: steps.length > 0,
      };
    }

    // a modal or drawer without an anchor of its own: the path starts at it
    const root = PORTAL_ROOTS.find((name) => node!.classList.contains(name));
    if (root) {
      return {
        selector: [`.${root}`, ...steps].join(" > "),
        element: target,
        fragile: true,
      };
    }

    steps.unshift(structuralStep(node));
    node = node.parentElement;
  }

  return { selector: steps.join(" > "), element: target, fragile: true };
};

/**
 * Selector for a picked element: the closest element with a stable attribute
 * (the target or an ancestor) that can be highlighted, or, when `exact` is set
 * or there is none, the target itself through a fragile structural selector.
 * An anchor without a box of its own (a modal's root) only scopes the path.
 */
export const pickElement = (target: Element, exact = false): IPickedElement => {
  if (!exact) {
    let node: Element | null = target;

    for (let depth = 0; node && node !== document.body; depth += 1) {
      if (depth >= MAX_DEPTH) break;

      const own = stableSelector(node);
      const rect = node.getBoundingClientRect();
      if (own && rect.width > 0 && rect.height > 0) {
        return {
          selector: scopedSelector(node, own),
          element: node,
          fragile: false,
        };
      }

      // never snap out of a modal onto the page behind it
      if (PORTAL_ROOTS.some((name) => node!.classList.contains(name))) break;

      node = node.parentElement;
    }
  }

  return exactSelector(target);
};

/**
 * Page element under a viewport point, skipping the help mode's own layer
 */
export const elementAtPoint = (x: number, y: number): Element | null =>
  document.elementsFromPoint(x, y).find((node) => !isInsideHelpLayer(node)) ??
  null;

export interface IRect {
  top: number;
  left: number;
  width: number;
  height: number;
}

/**
 * Part of the element inside the viewport, when some of it is really on top:
 * an element behind a modal or scrolled out of its container is not visible
 * even though it has a size.
 */
export const visibleRect = (element: Element): IRect | null => {
  const rect = element.getBoundingClientRect();
  // nothing under the help mode bar is visible
  const barHeight =
    parseFloat(
      getComputedStyle(document.documentElement).getPropertyValue(
        "--nh-help-bar-height",
      ),
    ) || 0;
  const top = Math.max(rect.top, barHeight);
  const left = Math.max(rect.left, 0);
  const bottom = Math.min(rect.bottom, window.innerHeight);
  const right = Math.min(rect.right, window.innerWidth);

  if (bottom - top < 2 || right - left < 2) return null;

  const inset = 2;
  const points: [number, number][] = [
    [(left + right) / 2, (top + bottom) / 2],
    [left + inset, top + inset],
    [right - inset, top + inset],
    [left + inset, bottom - inset],
    [right - inset, bottom - inset],
  ];

  const onTop = points.some(([x, y]) => {
    const hit = elementAtPoint(x, y);

    return !!hit && (hit === element || element.contains(hit));
  });

  if (!onTop) return null;

  return { top, left, width: right - left, height: bottom - top };
};

/**
 * First visible element the selector matches
 */
export const resolveElement = (
  selector: string,
): { element: Element; rect: IRect } | null => {
  for (const element of queryAll(selector)) {
    const rect = visibleRect(element);

    if (rect) return { element, rect };
  }

  return null;
};

/**
 * Whether a saved selector rests on the markup around a stable attribute
 * rather than on the attribute alone (see pickElement)
 */
export const isFragileSelector = (selector: string) =>
  selector.includes(" > ") ||
  /^(body|\.ant-modal-root|\.ant-drawer)\b/.test(selector);
