export default class Feature {
  static MICROMEDEX = "MICROMEDEX";
  static PRIMARYCARE = "PRIMARYCARE";
  static CONCILIATION = "CONCILIATION";
  static TEMP_CPOE_PERIOD = "TEMP_CPOE_PERIOD";
  static MULTIPLE_INTERVENTION = "MULTIPLE_INTERVENTION";
  static SOLUTION_FREQUENCY = "SOLUTION_FREQUENCY";
  static LOCK_CHECKED_PRESCRIPTION = "LOCK_CHECKED_PRESCRIPTION";
}
