export default class Feature {
  static MICROMEDEX = "MICROMEDEX";
  static PRIMARYCARE = "PRIMARYCARE";
  static NOHARMCARE = "NOHARMCARE";
  static CONCILIATION = "CONCILIATION";
  static TEMP_CPOE_PERIOD = "TEMP_CPOE_PERIOD";
  static MULTIPLE_INTERVENTION = "MULTIPLE_INTERVENTION";
}
