export default class Feature {
  static MICROMEDEX = "MICROMEDEX";
  static PRIMARYCARE = "PRIMARYCARE";
  static NOHARMCARE = "NOHARMCARE";
  static CONCILIATION = "CONCILIATION";
  static PRESCRIPTION_EXPIRATION_TAG = "PRESCRIPTION_EXPIRATION_TAG"; //temp
}
