export default class Permission {
  static ADMIN_DRUGS = "ADMIN_DRUGS";
  static ADMIN_DRUGS__OVERWRITE_ATTRIBUTES =
    "ADMIN_DRUGS__OVERWRITE_ATTRIBUTES";

  static ADMIN_EXAMS = "ADMIN_EXAMS";
  static ADMIN_EXAMS__COPY = "ADMIN_EXAMS__COPY";
  static ADMIN_EXAMS__MOST_FREQUENT = "ADMIN_EXAMS__MOST_FREQUENT";

  static ADMIN_FREQUENCIES = "ADMIN_FREQUENCIES";
  static ADMIN_ROUTES = "ADMIN_ROUTES";
  static ADMIN_SUBSTANCE_RELATIONS = "ADMIN_SUBSTANCE_RELATIONS";
  static ADMIN_SUBSTANCES = "ADMIN_SUBSTANCES";
  static ADMIN_SEGMENTS = "ADMIN_SEGMENTS";
  static ADMIN_UNIT_CONVERSION = "ADMIN_UNIT_CONVERSION";

  static ADMIN_PATIENT = "ADMIN_PATIENT";

  static ADMIN_USERS = "ADMIN_USERS";

  static ADMIN_INTEGRATION_REMOTE = "ADMIN_INTEGRATION_REMOTE";

  static ADMIN_INTERVENTION_REASON = "ADMIN_INTERVENTION_REASON";

  static ADMIN_NZERO = "ADMIN_NZERO";

  static WRITE_SEGMENT_SCORE = "WRITE_SEGMENT_SCORE";

  static INTEGRATION_UTILS = "INTEGRATION_UTILS";
  static INTEGRATION_STATUS = "INTEGRATION_STATUS";

  static READ_REPORTS = "READ_REPORTS";

  static READ_PRESCRIPTION = "READ_PRESCRIPTION";
  static WRITE_PRESCRIPTION = "WRITE_PRESCRIPTION";

  static WRITE_DRUG_ATTRIBUTES = "WRITE_DRUG_ATTRIBUTES";
  static WRITE_DRUG_SCORE = "WRITE_DRUG_SCORE";

  static READ_BASIC_FEATURES = "READ_BASIC_FEATURES";
  static WRITE_BASIC_FEATURES = "WRITE_BASIC_FEATURES";

  static READ_DISCHARGE_SUMMARY = "READ_DISCHARGE_SUMMARY";
  static WRITE_DISCHARGE_SUMMARY = "WRITE_DISCHARGE_SUMMARY";

  static READ_SUPPORT = "READ_SUPPORT";
  static WRITE_SUPPORT = "WRITE_SUPPORT";
  static ADMIN_SUPPORT = "ADMIN_SUPPORT";

  static READ_USERS = "READ_USERS";
  static WRITE_USERS = "WRITE_USERS";

  static READ_DISPENSATION = "READ_DISPENSATION";
  static WRITE_DISPENSATION = "WRITE_DISPENSATION";

  static MAINTAINER = "MAINTAINER";
  static MULTI_SCHEMA = "MULTI_SCHEMA";

  static READ_REGULATION = "READ_REGULATION";
  static WRITE_REGULATION = "WRITE_REGULATION";

  static WRITE_TAGS = "WRITE_TAGS";

  static READ_PROTOCOLS = "READ_PROTOCOLS";
  static WRITE_PROTOCOLS = "WRITE_PROTOCOLS";
}
