export default class ReportEnum {
  static PATIENT_DAY = "PATIENT_DAY";
  static PRESCRIPTION = "PRESCRIPTION";
  static PRESCRIPTION_AUDIT = "PRESCRIPTION_AUDIT";
  static INTERVENTION = "INTERVENTION";
  static ECONOMY = "ECONOMY";
  static PEC_INDICATORS_PANEL = "PEC_INDICATORS_PANEL";
}
