import type { Page } from "@playwright/test";

import { test, expect } from "../support/mockApi";

/**
 * Opening a modal of the prescription screen from the URL (links generated by
 * custom reports): ?modal=alertas, ?modal=exames[&fkexame=],
 * ?modal=evolucoes[&fkevolucao=]. The params are consumed once and removed.
 */

const NUMERIC_EXAM = {
  name: "Creatinina",
  value: 1.8,
  unit: "mg/dL",
  ref: "0,6 a 1,2",
  perc: null,
  date: "2024-01-02T03:04:05",
  alert: true,
  configured: false,
  text: false,
  source: "postgres",
  history: [
    {
      idExam: 555,
      value: 1.8,
      unit: "mg/dL",
      date: "2024-01-02T03:04:05",
      alert: true,
      min: 0.6,
      max: 1.2,
      configured: false,
      manual: false,
      admissionNumber: 9999,
      source: "postgres",
    },
    {
      idExam: 554,
      value: 1.1,
      unit: "mg/dL",
      date: "2024-01-01T03:04:05",
      alert: false,
      min: 0.6,
      max: 1.2,
      configured: false,
      manual: false,
      admissionNumber: 9999,
      source: "postgres",
    },
  ],
};

const note = (id: string, date: string, text: string) => ({
  id,
  admissionNumber: 9999,
  text,
  date,
  prescriber: "Fulano Beltrano",
  position: "Medico",
  form: null,
  template: null,
});

const RECENT_NOTE = note("776", "2024-01-03T08:00:00", "Evolucao mais recente");
const TARGET_NOTE = note("777", "2024-01-02T03:04:05", "Evolucao aberta pelo link");
const OLD_NOTE = note("700", "2023-12-20T10:00:00", "Evolucao antiga aberta pelo link");

/**
 * GET /notes/:admissionNumber/v2 serves the recent days with their notes and
 * the older day empty; ?date= loads one day (the mock ignores query strings
 * in handler keys, so the handler reads it).
 */
const installNotes = (mockApi: any) => {
  mockApi.override("GET /notes/:admissionNumber/v2", (route: any) => {
    const date = new URL(route.request().url()).searchParams.get("date");
    const data = date
      ? { notes: date === "2023-12-20" ? [OLD_NOTE] : [], dates: [], previousAdmissions: [] }
      : {
          notes: [RECENT_NOTE, TARGET_NOTE],
          dates: [
            { date: "2024-01-03", count: 1, roles: ["Medico"] },
            { date: "2024-01-02", count: 1, roles: ["Medico"] },
            { date: "2023-12-20", count: 1, roles: ["Medico"] },
          ],
          previousAdmissions: [],
        };

    return route.fulfill({ json: { status: "success", data } });
  });
};

const noteLine = (page: Page, id: string) =>
  page.locator(`.ant-modal [data-note-id="${id}"]`);

const waitForPrescription = async (page: Page) => {
  await expect(
    page.getByRole("heading", { name: "Prescrição nº 199 Liberada em" }),
  ).toBeVisible({ timeout: 15000 });
};

const expectParamsRemoved = async (page: Page) => {
  await expect(page).toHaveURL(/\/prescricao\/199$/);
};

test("opens the alerts report", async ({ page }) => {
  await page.goto("/prescricao/199?modal=alertas");
  await waitForPrescription(page);

  await expect(
    page.locator(".ant-modal").getByText("Relatório: Alertas").first(),
  ).toBeVisible();
  await expectParamsRemoved(page);
});

test("opens the exams modal on the linked exam", async ({ page, mockApi }) => {
  mockApi.override("GET /exams/:admissionNumber", {
    json: { status: "success", data: { creatinina: NUMERIC_EXAM } },
  });

  await page.goto("/prescricao/199?modal=exames&fkexame=555");
  await waitForPrescription(page);

  const modal = page.locator(".ant-modal");
  await expect(modal.getByRole("tab", { name: "Exames numéricos" })).toHaveAttribute(
    "aria-selected",
    "true",
  );

  // the exam is not configured: the filter that would hide it is turned off
  await expect(
    modal.getByRole("checkbox", { name: "Exibir somente exames configurados" }),
  ).not.toBeChecked();

  const typeRow = modal.locator('tr[data-row-key="creatinina"]');
  await expect(typeRow).toHaveClass(/highlight/);

  // the type row is expanded and the history entry with the fkexame is marked
  const highlighted = modal.locator(".ant-table-expanded-row tr.highlight");
  await expect(highlighted).toHaveCount(1);
  await expect(highlighted).toContainText("02/01/2024");

  await expectParamsRemoved(page);
});

test("warns when the linked exam is not among the loaded exams", async ({
  page,
  mockApi,
}) => {
  mockApi.override("GET /exams/:admissionNumber", {
    json: { status: "success", data: { creatinina: NUMERIC_EXAM } },
  });

  await page.goto("/prescricao/199?modal=exames&fkexame=1");
  await waitForPrescription(page);

  await expect(
    page.getByText(
      "Exame não localizado entre os exames carregados deste atendimento.",
    ),
  ).toBeVisible();
  await expect(
    page.locator(".ant-modal").getByRole("tab", { name: "Exames numéricos" }),
  ).toBeVisible();
});

test("opens the notes list with the linked note selected", async ({
  page,
  mockApi,
}) => {
  installNotes(mockApi);

  await page.goto("/prescricao/199?modal=evolucoes&fkevolucao=777");
  await waitForPrescription(page);

  const modal = page.locator(".ant-modal");
  await expect(modal.getByText("Evoluções", { exact: true })).toBeVisible();

  // the whole list is there, not only the linked note
  await expect(noteLine(page, "776")).toBeVisible();
  await expect(noteLine(page, "777")).toHaveClass(/active/);
  await expect(noteLine(page, "776")).not.toHaveClass(/active/);
  await expect(modal).toContainText(TARGET_NOTE.text);

  await expectParamsRemoved(page);
});

test("loads the day of an older linked note and selects it", async ({
  page,
  mockApi,
}) => {
  installNotes(mockApi);
  mockApi.override("GET /notes/single/:id", {
    json: { status: "success", data: OLD_NOTE },
  });

  await page.goto("/prescricao/199?modal=evolucoes&fkevolucao=700");
  await waitForPrescription(page);

  await expect(noteLine(page, "700")).toHaveClass(/active/);
  await expect(page.locator(".ant-modal")).toContainText(OLD_NOTE.text);
  expect(
    mockApi.requests.some((r) => r.path === "/notes/single/700"),
  ).toBeTruthy();
});

test("opens the clinical notes list without a note id", async ({ page }) => {
  await page.goto("/prescricao/199?modal=evolucoes");
  await waitForPrescription(page);

  await expect(
    page.locator(".ant-modal").getByText("Evoluções", { exact: true }),
  ).toBeVisible();
  await expectParamsRemoved(page);
});

test("ignores an unknown modal and drops the params", async ({ page }) => {
  await page.goto("/prescricao/199?modal=xyz");
  await waitForPrescription(page);

  await expectParamsRemoved(page);
  await expect(page.locator(".ant-modal-wrap:visible")).toHaveCount(0);
});
