name: Deploy Production
on:
  push:
    branches: [master]
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
      - name: get-npm-version
        id: package-version
        run: echo "current-version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      - uses: SocketDev/action@2d3f25590c6ed6ba11a9a14c064d962a3a04698f  # v1.3.1
        with:
          mode: firewall-free
      - name: npm ci
        run: sfw npm ci --ignore-scripts
      - name: npm run build
        run: npm run build
        env:
          VITE_APP_API_URL: ${{ secrets.REACT_APP_API_URL_PROD }}
          VITE_APP_SITE_TITLE: ${{ secrets.REACT_APP_SITE_TITLE_PROD }}
          VITE_APP_UPDOWN_LINK: ${{ secrets.REACT_APP_UPDOWN_LINK }}
          VITE_APP_PRISMIC_API_URL: ${{ secrets.REACT_APP_PRISMIC_API_URL }}
          VITE_APP_PRISMIC_TOKEN: ${{ secrets.REACT_APP_PRISMIC_TOKEN }}
          VITE_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          VITE_APP_SUPPORT_EMAIL: ${{ secrets.REACT_APP_SUPPORT_EMAIL }}
          VITE_APP_SUPPORT_LINK: ${{ secrets.REACT_APP_SUPPORT_LINK }}
          VITE_APP_ODOO_LINK: ${{ secrets.REACT_APP_ODOO_LINK }}
          VITE_APP_URL: ${{ secrets.REACT_APP_URL_PROD }}
          VITE_APP_VERSION: ${{ steps.package-version.outputs.current-version}}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a  # v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - name: Deploy Production to AWS
        run: aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_PROD }} --acl public-read
      - name: Set cache-control on index.html
        run: |
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_PROD }}/index.html s3://${{ secrets.AWS_S3_BUCKET_PROD }}/index.html \
            --metadata-directive REPLACE \
            --cache-control "max-age=0,no-cache,no-store,must-revalidate" \
            --content-type text/html \
            --acl public-read
