name: Deploy Test (Manual)
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: npm ci
        run: npm ci
      - name: npm run build
        run: npm run build
        env:
          VITE_APP_API_URL: ${{ secrets.REACT_APP_API_URL_TEST }}
          VITE_APP_SITE_TITLE: ${{ secrets.REACT_APP_SITE_TITLE_TEST }}
          VITE_APP_UPDOWN_LINK: ${{ secrets.REACT_APP_UPDOWN_LINK }}
          VITE_APP_PRISMIC_API_URL: ${{ secrets.REACT_APP_PRISMIC_API_URL }}
          VITE_APP_PRISMIC_TOKEN: ${{ secrets.REACT_APP_PRISMIC_TOKEN }}
          VITE_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          VITE_APP_SUPPORT_EMAIL: ${{ secrets.REACT_APP_SUPPORT_EMAIL }}
          VITE_APP_SUPPORT_LINK: ${{ secrets.REACT_APP_SUPPORT_LINK }}
          VITE_APP_ODOO_LINK: ${{ secrets.REACT_APP_ODOO_LINK }}
          VITE_APP_URL: ${{ secrets.REACT_APP_URL_TEST }}
          VITE_APP_VERSION: ${{ steps.package-version.outputs.current-version}}
      - name: Deploy Test to AWS
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete --exclude '.*' --exclude 'node_modules/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_TEST }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "dist"
      - name: Set cache-control on index.html
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: "s3://${{ secrets.AWS_S3_BUCKET_TEST }}/index.html"
          dest: "s3://${{ secrets.AWS_S3_BUCKET_TEST }}/index.html"
          flags: --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read
